# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mix7w4JCzjrzgVuMQsbKG57yTfd_VZjC
"""

import datetime as dt
import yfinance as yf
import matplotlib.pyplot as plt

start = dt.datetime(2026, 1, 1)
end = dt.datetime(2026, 3, 1)



df = yf.download("GOOG", start, end)
print("/n")
print(df.head(5))

print(df)
df.plot()
plt.show

# yf.pdr_override()
start = dt.datetime(2025, 1, 1)
end = dt.datetime(2026, 3, 1)

def get_stock_prices(ticker,start,end):
  try:
    df = yf.download(ticker, start, end)
    return df
  except Exception as e:
    print(f"An error occurred: {e}")
    return None

def plt_stock_prices(df):
  if df is not None:
    df["Close"].plot()
    plt.show()
  else:
    print("No data to plot")


start = dt.datetime(2025, 1, 1)
end = dt.datetime(2026, 3, 1)
df = get_stock_prices(["GOOG","AAPL","TSLA"], start, end)
# df_appl = get_stock_prices("AAPL", start, end)
# df_tsla = get_stock_prices("TSLA", start, end)
plt1 = plt_stock_prices(df)
# plt_stock_prices(df_appl)
# plt_stock_prices(df_tsla)

import datetime as dt
import yfinance as yf
import matplotlib.pyplot as plt

# plt.style.use('_mpl-gallery')
# plt.show()
# Get the funds data
spy = yf.Ticker("SPY").funds_data
print(spy.description)
print(spy.top_holdings)
# THis is
myportfolio = spy.top_holdings.index.tolist()
print(myportfolio)
# 1. Import the required libraries
start = dt.datetime(2025, 1, 1)
end = dt.datetime(2025, 4, 1)
df = get_stock_prices(myportfolio, start, end)
plt1 = plt_stock_prices(df)

# df_portfolio = yf.download(myportfolio, start, end)
# df_portfolio.to_excel("myportfolio2.xlsx")
# print(df_portfolio.head(5))